### ISSUE TITLE
Erro no Compass

### ISSUE THREAD

**Issue by rodrigo-brito** [wpbrasil/odin-gulp#3]
Coloquei o arquivo de configuração do Gulp em um tema local aqui, porém o compass retornou alguns erros de configuração de pastas. Parece que o mesmo não conseguiu identificar o arquivo de configuração (config.rb), que define as pastas do SASS. Ele retorna o seguinte erro:

```
[14:41:26] Starting 'compass'...
[14:41:26] /home/rodrigo/Development/odin/assets/css/bootstrap reloaded.
[14:41:26] Individual stylesheets must be in the sass directory.
[14:41:26] Plumber found unhandled error:
 Error in plugin 'gulp-compass'
Message:
    Compass failed
Details:
    fileName: /home/rodrigo/Development/odin/assets/sass/editor-style.scss
```

A task só é executada se definir uma configuração inline. 

```
compass({
    project: path.join(__dirname, '../assets'),
        css: 'css',
        sass: 'sass'
})
```

As permissões de leitura do arquivo estão bacanas, mas não faço ideia do que poderia ser.

**Comment by sandrojonathan** [comment]
Então o meu também está dando o mesmo erro, até o momento não consegui resolver, mas achei esse link aqui talvez possa ajudar. 

https://github.com/appleboy/gulp-compass/issues/61

**Comment by rodrigo-brito** [comment]
A issue está quase fazendo aniversário kkkk
@mirdnas resolvi deixando o valor da configuração inline como citado acima. Mas a origem do problema não faço a menor ideia.

**Comment by sandrojonathan** [comment]
Mais funcionou ?  O meu aqui quando faço dessa forma diz: 
path is not defined. 
Não sei muito utilizar isso; mas fez apenas essas configurações e funcionou normal?

**Comment by rodrigo-brito** [comment]
Tem que importar o path no topo:
`path = require('path');`

**Comment by sandrojonathan** [comment]
Funcionou. Obrigado Deus abençoe.

**Comment by rodrigo-brito** [comment]
Amém!

**Comment by amandagodoy** [comment]
Pessoal estou tendo o seguinte erro no meu projeto utilizando sass e compass:

compass watch --poll
Traceback (most recent call last):
        14: from C:/Ruby27-x64/bin/compass:23:in `<main>'
        13: from C:/Ruby27-x64/bin/compass:23:in `load'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/compass-1.1.0.alpha.3/bin/compass:19:in `<top (required)>'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/compass-1.1.0.alpha.3/bin/compass:8:in `fallback_load_path'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/compass-1.1.0.alpha.3/bin/compass:20:in `block in <top (required)>'
         9: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
         8: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/compass-1.1.0.alpha.3/lib/compass.rb:13:in `<top (required)>'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/compass-1.1.0.alpha.3/lib/compass.rb:13:in `each'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/compass-1.1.0.alpha.3/lib/compass.rb:14:in `block in <top (required)>'
         4: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
         3: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
         2: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/compass-core-1.1.0.alpha.3/lib/compass/core.rb:67:in `<top (required)>'
         1: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/compass-core-1.1.0.alpha.3/lib/compass/core/caniuse.rb:72: circular argument reference - browsers (SyntaxError)

**Comment by allysonsouza** [comment]
Olá @amandagodo,  parece algum problema com a instalação do compass, você chegou a tentar reinstalar o módulo no Ruby? Caso não, pode tentar usando os seguintes comandos em seu terminal:

```
gem uninstall compass
gem update --system
gem install compass
```

E uma curiosidade, você está dando manutenção em um site feito com Odin antigo, ou está criando algo novo?

**Comment by amandagodoy** [comment]
Se quiser dar uma olhada no meu projeto para tirar suas conclusões, pois como estou aprendendo não sei lhe dizer.

https://github.com/amandagodoy/Sass-Compas-descompilando-CSS/tree/main
